version: '3.8'  # Use version 3.8 for resource constraints

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          memory: 3G  # Set the upper memory limit to 3GB
        reservations:
          memory: 3G  # Reserve 3GB memory for this container
    # No need to have nginx here

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
