version: '3.8'  # Use version 3.8 for resource constraints
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          memory: 3G  # Set the upper memory limit to 1GB (or higher if needed)
        reservations:
          memory: 3G  # Reserve 1GB memory for this container to start with
    depends_on:
      - nginx

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
